#pragma config(Sensor, S1,     Sound,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     Gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S3,     Camera,         sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     Touch,          sensorEV3_Touch)
#pragma config(Motor,  motorA,          CLAW,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          LEFT,          tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RIGHT,         tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void Wander();
void MoveOutOfBase();
void MoveForward();
void Reverse();
void PivotRight();
void PivotLeft();
void WanderLeft();
void WanderRight();
void MoveTowardsEgg();
void StopAtEgg();
void PushEggTowardsNest(int nest);
void PushEggIntoNest();

task main()
{
	int base = SensorValue[S2]; //This calibrates which direction the base is on the compass.
	MoveOutOfBase();

	while(true)
	{
		Wander();

		if(SensorValue[S1]<70)
		{
			MoveTowardsEgg();
			StopAtEgg();
			PushEggTowardsNest(base);
			PushEggIntoNest();
	  }
	}
}

void Wander()
{
	if(SensorValue[S4])
	{
		Reverse();
		switch(abs(rand())%2)
		{
			case 0: PivotLeft(); break;
			case 1: PivotRight(); break;
		}
	}

	switch(abs(rand())%3)
	{
		case 0: MoveForward(); break;
		case 1:	WanderLeft(); break;
		case 2: WanderRight(); break;
	}

}

void MoveOutOfBase()
{
	setMotorSpeed(motorB, 80);		//Set the leftMotor (motor1) to half power (50)
	setMotorSpeed(motorC, 80);  	//Set the rightMotor (motor6) to half power (50)
	sleep(1000);									//Wait for 1 seconds before continuing on in the program.
}

void MoveForward()
{
	setMotorSpeed(motorB, 80);		//Set the leftMotor (motor1) to half power (50)
	setMotorSpeed(motorC, 80);  	//Set the rightMotor (motor6) to half power (50)
	sleep(rand()%1000);						//Wait for a random amount of time before continuing on in the program.
}

void Reverse()
{
	setMotorSpeed(motorA, 0);
	setMotorSpeed(motorB, -80);	//Set the leftMotor (motor1) to high power forward (80)
	setMotorSpeed(motorC, -80);	//Set the rightMotor (motor6) to high power forward (80)
	sleep(1000);
}

void WanderRight()
{
	setMotorSpeed(motorB, 0);			//Set the leftMotor (motor1) to Off
	setMotorSpeed(motorC, 100);  	//Set the rightMotor (motor6) to full power forward (100)
	sleep(rand()%1000);						//Wait a random amount of time before continuing on in the program.
}

void WanderLeft()
{
	setMotorSpeed(motorB, 100);		//Set the leftMotor (motor1) to full power forward (100)
	setMotorSpeed(motorC, 0);  		//Set the rightMotor (motor6) to full power reverse (-100)
	sleep(rand()%1000);						//Wait a random amount of time before continuing on in the program.
}

void PivotRight()
{
	setMotorSpeed(motorB, -100);	//Set the leftMotor (motor1) to full power forward (100)
	setMotorSpeed(motorC, 100); 	//Set the rightMotor (motor6) to full power reverse (-100)
	sleep(500);										//Wait half a second before continuing on in the program.

}

void PivotLeft()
{
	setMotorSpeed(motorB, 100);		//Set the leftMotor (motor1) to full power forward (100)
	setMotorSpeed(motorC, -100);  //Set the rightMotor (motor6) to full power reverse (-100)
	sleep(500);										//Wait half a second before continuing on in the program.

}

void MoveTowardsEgg()
{
	while(SensorValue[S1]>20)
	{
		setMotorSpeed(motorB, 20);
		setMotorSpeed(motorC, 20);
	}
}

void StopAtEgg()
{
	setMotorSpeed(motorA, 50);
  setMotorSpeed(motorB, 0);			//Set the leftMotor (motor1) to high power forward (80)
	setMotorSpeed(motorC, 0);			//Set the rightMotor (motor6) to high power forward (80)
	sleep(500);

	setMotorSpeed(motorA, 0);
}

void PushEggTowardsNest(int nest)
{
	while(SensorValue[S2]!=nest)
	{
		setMotorSpeed(motorB, 20);
		setMotorSpeed(motorC, -20);
	}
}

void PushEggIntoNest()
{
	while(SensorValue[S3]==1)
	{
		setMotorSpeed(motorB, 80);	//Set the leftMotor (motor1) to high power forward (80)
		setMotorSpeed(motorC, 80);	//Set the rightMotor (motor6) to high power forward (80)
  }

  sleep(500);										//Continues forward for another half of a second

  setMotorSpeed(motorA, -50);
  sleep(500);
	Reverse();

	PivotLeft();

}
