#pragma config(Sensor, S1,     rightTouch,     sensorEV3_Touch)
#pragma config(Sensor, S2,     Gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S3,     Camera,         sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     leftTouch,      sensorEV3_Touch)
#pragma config(Motor,  motorB,          LEFT,          tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RIGHT,         tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void Wander();
void MoveOutOfBase();
void MoveForward();
void Reverse();
void PivotRight();
void PivotLeft();
void WanderLeft();
void WanderRight();
void PushEggIntoNest();

task main()
{
	MoveOutOfBase();
	while(true)
	{
		Wander();
		//if()/*you find an egg*/
		//{
			PushEggIntoNest();
		//}
	}
}

void Wander()
{
	while(!SensorValue[S1] && !SensorValue[S4])
	{
		switch(abs(rand())%3)
		{
		case 0: MoveForward(); break;
		case 1:	WanderLeft(); break;
		case 2: WanderRight(); break;
		}
	}

	Reverse();
	switch(abs(rand())%2)
	{
		case 0: PivotLeft(); break;
		case 1: PivotRight(); break;
	}
}

void MoveOutOfBase()
{
	setMotorSpeed(motorB, 80);		//Set the leftMotor (motor1) to half power (50)
	setMotorSpeed(motorC, 80);  	//Set the rightMotor (motor6) to half power (50)
	sleep(1000);									//Wait for 1 seconds before continuing on in the program.
}

void MoveForward()
{
	setMotorSpeed(motorB, 80);		//Set the leftMotor (motor1) to half power (50)
	setMotorSpeed(motorC, 80);  	//Set the rightMotor (motor6) to half power (50)
	sleep(rand()%1000);						//Wait for a random amount of time before continuing on in the program.
}

void Reverse()
{
	setMotorSpeed(motorB, -80);	//Set the leftMotor (motor1) to high power forward (80)
	setMotorSpeed(motorC, -80);	//Set the rightMotor (motor6) to high power forward (80)
	sleep(1000);
}

void WanderRight()
{
	setMotorSpeed(motorB, 0);			//Set the leftMotor (motor1) to Off
	setMotorSpeed(motorC, 100);  	//Set the rightMotor (motor6) to full power forward (100)
	sleep(rand()%1000);						//Wait a random amount of time before continuing on in the program.
}

void WanderLeft()
{
	setMotorSpeed(motorB, 100);		//Set the leftMotor (motor1) to full power forward (100)
	setMotorSpeed(motorC, 0);  		//Set the rightMotor (motor6) to full power reverse (-100)
	sleep(rand()%1000);						//Wait a random amount of time before continuing on in the program.
}

void PivotRight()
{
	setMotorSpeed(motorB, -100);	//Set the leftMotor (motor1) to full power forward (100)
	setMotorSpeed(motorC, 100); 	//Set the rightMotor (motor6) to full power reverse (-100)
	sleep(500);										//Wait half a second before continuing on in the program.

}

void PivotLeft()
{
	setMotorSpeed(motorB, 100);		//Set the leftMotor (motor1) to full power forward (100)
	setMotorSpeed(motorC, -100);  //Set the rightMotor (motor6) to full power reverse (-100)
	sleep(500);										//Wait half a second before continuing on in the program.

}

void PushEggIntoNest()
{
	while(SensorValue[S3]==1)
	{
		setMotorSpeed(motorB, 80);	//Set the leftMotor (motor1) to high power forward (80)
		setMotorSpeed(motorC, 80);	//Set the rightMotor (motor6) to high power forward (80)
  }

  sleep(500);										//Continues forward for another half of a second

  setMotorSpeed(motorB, 0);			//Set the leftMotor (motor1) to high power forward (80)
	setMotorSpeed(motorC, 0);			//Set the rightMotor (motor6) to high power forward (80)
	sleep(250);										//Wait a quarter of a second before continuing on in the program.

	Reverse();


}
